services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./PostgreSQLScript.sql:/docker-entrypoint-initdb.d/PostgreSQLScript.sql
    networks:
      - my_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.8
    container_name: todoapp
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/TodoApplicationDatabase"
    ports:
      - "8080:8080"
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge